version: 2
updates:
  # Enable version updates for npm (Frontend dependencies)
  - package-ecosystem: "npm"
    directory: "/apps/vue"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "RumenDamyanov"
    commit-message:
      prefix: "vue"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/apps/react"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "RumenDamyanov"
    commit-message:
      prefix: "react"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/apps/angular"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "RumenDamyanov"
    commit-message:
      prefix: "angular"
      include: "scope"

  # Enable version updates for Go modules (Backend submodule)
  - package-ecosystem: "gomod"
    directory: "/backend/go-chess"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "RumenDamyanov"
    commit-message:
      prefix: "backend"
      include: "scope"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "monthly"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "RumenDamyanov"
    commit-message:
      prefix: "docker"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
    open-pull-requests-limit: 2
    reviewers:
      - "RumenDamyanov"
    commit-message:
      prefix: "ci"
